---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.81bedfb8-bcac-4bf4-8238-764fa45ed2c6

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.de200000-d502-46be-be14-eee3c93a1f55.Boolean.Property
        operator: ne
        operands:
            - "false"
