---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: AutoTest.target-group.4ce6abb3-2f75-4585-99eb-2f15e01b8354

description: Target group 1

conditions:
  allOf:
    - property:
        name: AutoTest.cfc4138c-ff7f-4f1c-b87b-1851e6bfd687.Boolean.Property
        operator: ne
        operands:
            - "false"
