---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: AutoTest.7a1783c4-1850-4a58-beed-1203a8c4c11f.Boolean.Flag

enabled: false

stickinessProperty: stickiness

defaultValue: true

conditions: []
